export const PAGE_SIZE = 5;
export const LIGHT_MODE = "light",
	DARK_MODE = "dark",
	AUTO_MODE = "auto";
export const DEFAULT_THEME = AUTO_MODE;
export const BANNER_HEIGHT = 28;
export const BANNER_HEIGHT_EXTEND = 17;
export const BANNER_HEIGHT_HOME: number = BANNER_HEIGHT + BANNER_HEIGHT_EXTEND;
export const DEFAULT_BANNER_ASPECT_RATIO = 16 / 9;
export const MAIN_PANEL_OVERLAPS_BANNER_HEIGHT = 3.5;
export const PAGE_WIDTH = 75;
